function x = impact_model(q1,q2,q3,dq1,dq2,dq3)
%IMPACT_MODEL
%    X = IMPACT_MODEL(Q1,Q2,Q3,DQ1,DQ2,DQ3)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    28-Nov-2018 17:27:21

t2 = q1.*2.0;
t3 = q2.*2.0;
t7 = q3.*2.0;
t4 = t3-t7;
t5 = cos(t4);
t6 = t5.*4.0;
t8 = t2-t3;
t9 = cos(t8);
t10 = t9.*2.0;
t11 = t6+t10-1.9e1;
t12 = 1.0./t11;
t13 = q1-q2;
t14 = cos(t13);
x = [q2;q1;q3;dq2./(t6+cos(q2.*-2.0+t2).*2.0-1.9e1)-dq1.*t12.*(t14.*1.8e1-cos(q1+q2-t7).*4.0);dq1.*t12.*(t9.*-2.0e1+cos(t2-t7).*4.0+1.0)+dq2.*t12.*t14.*2.0;dq3-dq2.*t12.*cos(q2-q3).*2.0+dq1.*t12.*(cos(q1-q3).*-2.4e1+cos(q1+q3-t3).*2.4e1+cos(q1.*-3.0+q3+t3).*2.0)];
