function dx_tilde = swing_phase_MPFL(qb1,qb2,theta,dqb1,dqb2,sigma_N,v1,v2)
%SWING_PHASE_MPFL
%    DX_TILDE = SWING_PHASE_MPFL(QB1,QB2,THETA,DQB1,DQB2,SIGMA_N,V1,V2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    25-Nov-2018 02:06:47

t2 = qb1-qb2;
t3 = cos(t2);
t4 = cos(qb1);
t5 = t3.*5.0;
t6 = t4.*1.0e1;
t7 = t5+t6-3.5e1;
t8 = 1.0./t7;
t9 = t3.*2.5;
dx_tilde = [dqb1;dqb2;-sigma_N.*t8-dqb2.*t8.*(t9-1.25)-dqb1.*t8.*(t4.*5.0+t9-3.125e1);v1;v2;sin(qb1+theta).*-3.18825e2+sin(qb2+theta).*2.4525e1+sin(theta).*4.905e1];
